name: CI

on:
  pull_request:
    branches:
      - development

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - name: Instalação de dependências
        run: bun install

      - name: Rodando os Testes
        run: bun test

      - name: Build
        run: bun build index.ts

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: gabrielfrahm/ci:latest