name: CI

on:
  pull_request:
    branches:
      - development

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Instalação de dependências
        run: bun install
      - name: Rodando os Testes
        run: bun test
      - name: Build
        run: bun build index.ts