name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Instalação de dependências
        run: bun install
      - name: Build
        run: bun build index.ts